const tarotData = [
    { id: 0, file: "00.png", name: "0・ⅩⅩⅡ THE SOURCE", theme: "すべてはすべて" },
    { id: 1, file: "01.png", name: "Ⅰ INITIATION", theme: "すべては創造" },
    { id: 2, file: "02.png", name: "Ⅱ THE VEIL", theme: "すべてはコントラスト" },
    { id: 3, file: "03.png", name: "Ⅲ NATURE", theme: "すべてはサイクルで動いている" },
    { id: 4, file: "04.png", name: "Ⅳ ORDER", theme: "すべては形" },
    { id: 5, file: "05.png", name: "Ⅴ AWAKENING", theme: "自己の探求" },
    { id: 6, file: "06.png", name: "Ⅵ HARMONY", theme: "すべては惹かれ合う" },
    { id: 7, file: "07.png", name: "Ⅶ THE CHARIOT", theme: "すべては道" },
    { id: 8, file: "08.png", name: "Ⅷ EQUIRIBRIUM", theme: "すべてはバランス" },
    { id: 9, file: "09.png", name: "Ⅸ RECLUSE", theme: "すべては目撃される" },
    { id: 10, file: "010.png", name: "Ⅹ THE SPHINX", theme: "すべては回転している" },
    { id: 11, file: "011.png", name: "Ⅺ PRESENCE", theme: "すべては釣り合っている" },
    { id: 12, file: "012.png", name: "Ⅻ THE QUESTION", theme: "私は何者か？" },
    { id: 13, file: "013.png", name: "ⅩⅢ THE CROSSING", theme: "すべては変容" },
    { id: 14, file: "014.png", name: "ⅩⅣ ALCHEMY", theme: "すべてはエッセンス" },
    { id: 15, file: "015.png", name: "ⅩⅤ ENERGY", theme: "すべてはパワー" },
    { id: 16, file: "016.png", name: "ⅩⅥ THE TOWER", theme: "すべては浄化される" },
    { id: 17, file: "017.png", name: "ⅩⅦ THE STAR", theme: "すべては繋がっている" },
    { id: 18, file: "018.png", name: "ⅩⅧ THE MOON", theme: "すべては反射する" },
    { id: 19, file: "019.png", name: "ⅩⅨ THE SUN", theme: "すべては光" },
    { id: 20, file: "020.png", name: "ⅩⅩ THE ANGEL", theme: "すべては響き渡る" },
    { id: 21, file: "021.png", name: "ⅩⅩⅠ THE UNIVERSE", theme: "すべては巡る" }
];